/// ***************************************************************************
/// Pacmio Research Enivironment
/// Copyright 2001-2008, 2014-2021 Xu Li - me@xuli.us
/// 
/// ***************************************************************************

using System;
using System.Collections.Generic;

namespace Pacmio
{
    /// <summary>
    /// Decision is generated by the previous bar,
    /// and only one decision per bar
    /// but execution can happen multi-time within the bar per
    /// the decision's price target -- uncertainty, what if the 
    /// next bar engulfs all three prices?
    /// </summary>
    public interface IDecision
    {
        Bar DecisionBar { get; }

        double ProfitTakePrice { get; }

        double StopLossPrice { get; }
    }
}
